#!/bin/bash
if [ -z "$1" ]; then
    echo "error vanilla 23"
    exit 23
fi

if command -v xclip &>/dev/null; then
    cat "$1" | xclip -selection clipboard || { echo "error vanilla 101"; exit 101; }
elif command -v wl-copy &>/dev/null; then
    cat "$1" | wl-copy || { echo "error vanilla 102"; exit 102; }
else
    echo "error vanilla 100"
    exit 100
fi
